In [2]:
# importing pandas library
import pandas as pd

In [3]:
# create a sample data set
data = {'Age': [66, 32,27, 40, 51, 22], 
        'Owned_House': ['yes', 'yes', 'no', 'no', 'yes', 'yes'],
        'Salary': [54000, 321250, 29120, 46000, 61000, 52000],
        'Martial_status': ['widowed', 'married', 'married', 'single', 'divorced', 'single'],
        'Distance to the nearest town(km)': [5.4, 10.2, 6.7, 5.7, 15, 26.5]}
        
# creating a dataframe from the data
df = pd.DataFrame(data)

# display the dataframe
df

   Age Owned_House  Salary Martial_status  Distance to the nearest town(km)
0   66         yes   54000        widowed                               5.4
1   32         yes  321250        married                              10.2
2   27          no   29120        married                               6.7
3   40          no   46000         single                               5.7
4   51         yes   61000       divorced                              15.0
5   22         yes   52000         single                              26.5

In [4]:
# checking the data types of the columns
data_types = df.dtypes

data_types

Age                                   int64
Owned_House                             str
Salary                                int64
Martial_status                          str
Distance to the nearest town(km)    float64
dtype: object

In [6]:
# checking the data types of the columns
Age_data_type = df['Age'].dtype
print(f"The data type of the 'Age' column is: {Age_data_type}")

The data type of the 'Age' column is: int64

In [9]:
# retrieve the particular data types by using .select_dtypes() method 
select_attributes = df.select_dtypes(include=['object', 'float64'])
select_attributes

C:\Users\usman\AppData\Local\Temp\ipykernel_20300\2266242105.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  select_attributes = df.select_dtypes(include=['object', 'float64'])

  Owned_House Martial_status  Distance to the nearest town(km)
0         yes        widowed                               5.4
1         yes        married                              10.2
2          no        married                               6.7
3          no         single                               5.7
4         yes       divorced                              15.0
5         yes         single                              26.5

 **Here above in the output the data shows 'Nominal data ' which have attributes namely Owned_House , Martial_status. Continous data in the output for attribute for 'Distance to the nearest town(km)**

In [17]:
# Example 1: Finding missing data with Boolean results
import pandas as pd
#Importing numpy library
import numpy as np

data = {'Age': [np.nan, 32, 27, 40, 51, 22],
        'Owned_House': ['yes', 'yes', 'no',np.nan, 'yes', 'yes'],
        'Salary': [54000, 321250, 29120, 46000, 61000, 52000],
        'Martial_status': ['widowed', np.nan,np.nan, 'single', 'divorced', 'single'],
        'Distance to the nearest town(km)': [5.4, 10.2, 6.7, np.nan, 15, 26.5]}


df = pd.DataFrame(data)

df

#checking null values gives TRUE 
print(df.isnull())

#checking non missing value notnull()
print(df.notnull())

     Age  Owned_House  Salary  Martial_status  \
0   True        False   False           False
1  False        False   False            True
2  False        False   False            True
3  False         True   False           False
4  False        False   False           False
5  False        False   False           False

   Distance to the nearest town(km)
0                             False
1                             False
2                             False
3                              True
4                             False
5                             False
     Age  Owned_House  Salary  Martial_status  \
0  False         True    True            True
1   True         True    True           False
2   True         True    True           False
3   True        False    True            True
4   True         True    True            True
5   True         True    True            True

   Distance to the nearest town(km)
0                              True
1                              True
2                              True
3                             False
4                              True
5                              True